# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-16 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btaxsaveinputs',
            name='job_ids',
        ),
        migrations.AddField(
            model_name='btaxsaveinputs',
            name='job_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
