# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-05 20:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btax', '0002_btaxoutputurl_webapp_vers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btaxsaveinputs',
            name='tax_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
