# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-16 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btax', '0002_auto_20180816_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btaxsaveinputs',
            name='jobs_not_ready',
        ),
    ]
