# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-21 14:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid
import webapp.apps.btax.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxbrain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicElasticitySaveInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(blank=True, default='PUF', max_length=20, null=True)),
                ('elastic_gdp', webapp.apps.btax.models.CommaSeparatedField(blank=True, default=None, max_length=200, null=True)),
                ('first_year', models.IntegerField(default=None, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2015, 1, 1, 0, 0, tzinfo=utc))),
                ('micro_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxbrain.TaxBrainRun')),
            ],
            options={
                'permissions': (('view_inputs', 'Allowed to view Taxbrain.'),),
            },
        ),
        migrations.CreateModel(
            name='TaxBrainElastRun',
            fields=[
                ('outputs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('aggr_outputs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('error_text', models.CharField(blank=True, default=None, max_length=4000, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2015, 1, 1, 0, 0, tzinfo=utc))),
                ('exp_comp_datetime', models.DateTimeField(default=datetime.datetime(2015, 1, 1, 0, 0, tzinfo=utc))),
                ('job_id', models.UUIDField(blank=True, default=None, null=True)),
                ('upstream_vers', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('webapp_vers', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('inputs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='dynamic.DynamicElasticitySaveInputs')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
