# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-05 20:04


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0016_dynamicbehaviorsaveinputs_be_subinc_wrt_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicbehaviorsaveinputs',
            name='tax_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicelasticitysaveinputs',
            name='tax_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicsaveinputs',
            name='tax_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
