# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0019_auto_20180222_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicbehaviorsaveinputs',
            name='data_source',
            field=models.CharField(blank=True, default=b'PUF', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dynamicelasticitysaveinputs',
            name='data_source',
            field=models.CharField(blank=True, default=b'PUF', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dynamicsaveinputs',
            name='data_source',
            field=models.CharField(blank=True, default=b'PUF', max_length=20, null=True),
        ),
    ]
