# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-16 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0019_auto_20180216_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicbehaviorsaveinputs',
            old_name='fields',
            new_name='input_fields',
        ),
        migrations.RenameField(
            model_name='dynamicbehaviorsaveinputs',
            old_name='raw_fields',
            new_name='raw_input_fields',
        ),
    ]
