# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=False)),
                ('confirm_key', models.UUIDField(default=uuid.uuid4)),
                ('subscribe_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
