# -*- coding: utf-8 -*-


from django.db import models, migrations
import django.core.validators
import webapp.apps.taxbrain.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSaveInputs',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fica', models.FloatField(default=0.153, null=True, blank=True)),
                ('soc_max', models.FloatField(default=None, null=True, blank=True)),
                ('total_ira_deduc', models.FloatField(default=None, null=True, blank=True)),
                ('student_loan_deduc', models.FloatField(default=None, null=True, blank=True)),
                ('archer_msa_deduc', models.FloatField(default=None, null=True, blank=True)),
                ('deduc_half_self_employ', models.FloatField(default=None, null=True, blank=True)),
                ('self_employ_health_deduc', models.FloatField(default=None, null=True, blank=True)),
                ('keogh_sep_deduc', models.FloatField(default=None, null=True, blank=True)),
                ('forfeit_int_penalty', models.FloatField(default=None, null=True, blank=True)),
                ('alimony_paid', models.FloatField(default=None, null=True, blank=True)),
                ('moving_exp_deduc', models.FloatField(default=None, null=True, blank=True)),
                ('other_adjust', models.FloatField(default=None, null=True, blank=True)),
                ('foreign_housing_adjust', models.FloatField(default=None, null=True, blank=True)),
                ('reservist_performing_artist', models.FloatField(default=None, null=True, blank=True)),
                ('foreign_earned_inc_exemp', models.FloatField(default=None, null=True, blank=True)),
                ('standard_amount', models.FloatField(default=None, null=True, blank=True)),
                ('additional_aged', models.FloatField(default=None, null=True, blank=True)),
                ('medical_floor', models.FloatField(default=0.075, null=True, blank=True)),
                ('state_haircut', models.FloatField(default=None, null=True, blank=True)),
                ('state_limit', models.FloatField(default=None, null=True, blank=True)),
                ('casualty_floor', models.FloatField(default=0.1, null=True, blank=True)),
                ('misc_floor', models.FloatField(default=0.02, null=True, blank=True)),
                ('charity_ceiling_cash', models.FloatField(default=0.5, null=True, blank=True)),
                ('charity_ceiling_assets', models.FloatField(default=0.3, null=True, blank=True)),
                ('item_phase_out_threshold', models.FloatField(default=None, null=True, blank=True)),
                ('item_phase_out_rate', models.FloatField(default=0.03, null=True, blank=True)),
                ('max_perc_forfeited', models.FloatField(default=0.08, null=True, blank=True)),
                ('long_term_cap', models.FloatField(default=None, null=True, blank=True, choices=[(0.15, b'Threshold 1'), (0.25, b'Threshold 2'), (0.28, b'Threshold 3')])),
                ('dividends', models.FloatField(default=None, null=True, blank=True, choices=[(0.0, b'Threshold 1'), (0.15, b'Threshold 2'), (0.2, b'Threshold 3')])),
                ('medicare_unearned_inc_rate', models.FloatField(default=0.038, null=True, blank=True)),
                ('medicare_unearned_inc_threshold', models.FloatField(default=None, null=True, blank=True)),
                ('income_tax_rate', models.FloatField(default=None, null=True, blank=True, choices=[(0.0, b'Threshold 1'), (0.0, b'Threshold 2'), (0.0, b'Threshold 3'), (0.0, b'Threshold 4'), (0.0, b'Threshold 5'), (0.0, b'Threshold 6')])),
                ('amt_amount', models.FloatField(default=None, null=True, blank=True)),
                ('amt_phase_out', models.FloatField(default=0.025, null=True, blank=True)),
                ('amt_phase_out_start', models.FloatField(default=None, null=True, blank=True)),
                ('amt_rate', models.FloatField(default=0.26, null=True, blank=True)),
                ('individual_surtax', models.FloatField(default=0.02, null=True, blank=True)),
                ('individual_threshold', models.FloatField(default=None, null=True, blank=True)),
                ('eitc_credit_rate', models.FloatField(default=None, null=True, blank=True)),
                ('eitc_phase_out_rate', models.FloatField(default=None, null=True, blank=True)),
                ('eitc_phase_out_threshold', models.FloatField(default=None, null=True, blank=True)),
                ('child_max_credit', models.FloatField(default=None, null=True, blank=True)),
                ('child_phase_out_rate', models.FloatField(default=0.05, null=True, blank=True)),
                ('child_phase_out_threshold', models.FloatField(default=None, null=True, blank=True)),
                ('personal_exemp_amount', models.FloatField(default=None, null=True, blank=True)),
                ('phase_out', models.FloatField(default=0.02, null=True, blank=True)),
                ('phase_out_threshold', models.FloatField(default=None, null=True, blank=True)),
                ('additional_child_amount', models.FloatField(default=None, null=True, blank=True)),
                ('additional_qualify_no_child', models.FloatField(default=3, null=True, blank=True)),
                ('gross_income', models.FloatField(default=None, null=True, blank=True, choices=[(0.5, b'Threshold 1'), (0.85, b'Threshold 2')])),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OutputUrl',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('unique_inputs', models.ForeignKey(default=None, to='taxbrain.TaxSaveInputs')),
                ('uuid', models.UUIDField(null=True, default=None, editable=False, max_length=32, blank=True, unique=True)),
                ('taxcalc_vers', models.CharField(default=None, max_length=50, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AlterModelOptions(
            name='taxsaveinputs',
            options={'permissions': (('view_inputs', 'Allowed to view input page.'),)},
        ),
        migrations.AlterModelOptions(
            name='taxsaveinputs',
            options={'permissions': (('view_inputs', 'Allowed to view Taxbrain.'),)},
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='tax_result',
            field=models.TextField(default=None, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='inflation',
            field=models.FloatField(default=None, null=True, blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='medical_inflation',
            field=models.FloatField(default=None, null=True, blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='personal_exemp_amount',
            new_name='II_em',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='II_em',
            field=models.FloatField(default=None, null=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='phase_out_threshold',
            new_name='II_em_ps_0',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='II_em_ps_0',
            field=models.FloatField(default=None, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='inflation_years',
            field=models.FloatField(default=None, null=True, blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='medical_years',
            field=models.FloatField(default=None, null=True, blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='state_limit',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='deduc_half_self_employ',
            new_name='deduc_self_employ',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='dividends',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='long_term_cap',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='medicare_unearned_inc_rate',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='medicare_unearned_inc_threshold',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='soc_max',
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_rt1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_rt3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_rt2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd1_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd3_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd2_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_rt1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_rt3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_rt2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_thd1_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_thd2_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMED_trt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMED_thd_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='NIIT_thd_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_rt7',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_thd50_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_thd50_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_Income_c',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_percentage1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='gross_income',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='income_tax_rate',
            new_name='II_prt',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='II_prt',
            field=models.FloatField(default=None, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_rt1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_rt2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_rt3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_rt5',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_rt6',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk1_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk2_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk3_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk4_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk5_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk6_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='additional_child_amount',
            new_name='additional_child_rate',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='additional_qualify_no_child',
            new_name='qualify_number_child',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='archer_msa_deduc',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='foreign_housing_adjust',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='moving_exp_deduc',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='other_adjust',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='reservist_performing_artist',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='state_haircut',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='total_ira_deduc',
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='NIIT_trt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_thd50_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_thd50_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_percentage2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_thd85_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_thd85_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_thd85_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMED_thd_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMED_thd_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMED_thd_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_em_ps_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_em_ps_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_em_ps_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='additional_aged',
            new_name='additional_aged_single',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='standard_amount',
            new_name='standard_amount_single',
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_Aged_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_Aged_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='item_phase_out_threshold',
            new_name='item_phase_out_threshold_single',
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='ID_ps_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='ID_ps_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='ID_ps_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_thd1_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_thd1_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_thd1_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_thd2_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_thd2_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_thd2_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd1_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd1_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd1_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd3_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd3_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd3_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd2_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd2_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd2_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='NIIT_thd_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='NIIT_thd_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='NIIT_thd_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk1_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk1_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk1_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk2_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk2_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk2_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk3_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk3_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk3_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk4_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk4_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk4_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk5_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk5_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk5_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk6_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk6_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk6_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='amt_amount',
            new_name='amt_amount_single',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='amt_phase_out',
            new_name='amt_phase_out_rate',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='amt_phase_out_start',
            new_name='amt_phase_out_start_single',
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_em_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_em_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_em_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_em_ps_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_em_ps_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_em_ps_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='child_phase_out_threshold',
            new_name='child_phase_out_threshold_single',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='eitc_credit_rate',
            new_name='eitc_credit_rate_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='eitc_phase_out_rate',
            new_name='eitc_phase_out_rate_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='eitc_phase_out_threshold',
            new_name='eitc_phase_out_threshold_0',
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CTC_ps_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CTC_ps_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CTC_ps_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_rt_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_rt_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_prt_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_prt_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_prt_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_ps_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_ps_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_ps_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='II_em',
            field=models.CharField(blank=True, max_length=400, null=True, validators=[django.core.validators.RegexValidator(regex=b'\\d*\\.\\d+|\\d+', message=b'Enter only numbers separated by commas.', code=b'invalid_values')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='II_em_ps_0',
            field=models.FloatField(default=None, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='II_em',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator(regex=b'\\d*\\.\\d+|\\d+', message=b'Enter only numbers separated by commas.')]),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='phase_out',
            new_name='_II_prt',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='_II_prt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='additional_aged_single',
            new_name='STD_Aged_2',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='STD_Aged_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='additional_child_rate',
            new_name='ACTC_rt',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ACTC_rt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='alimony_paid',
            new_name='ALD_Alimony_HC',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ALD_Alimony_HC',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='amt_amount_single',
            new_name='AMT_em_0',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='AMT_em_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='amt_phase_out_rate',
            new_name='AMT_prt',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='AMT_prt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.025, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='amt_phase_out_start_single',
            new_name='AMT_em_ps_0',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='AMT_em_ps_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='amt_rate',
            new_name='AMT_trt1',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='AMT_trt1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.26, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='casualty_floor',
            new_name='ID_Casualty_frt',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_Casualty_frt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.1, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='charity_ceiling_assets',
            new_name='ID_Charity_crt_Asset',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_Charity_crt_Asset',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.3, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='charity_ceiling_cash',
            new_name='ID_Charity_crt_Cash',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_Charity_crt_Cash',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.5, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='child_max_credit',
            new_name='CTC_c',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='CTC_c',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='child_phase_out_rate',
            new_name='CTC_prt',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='CTC_prt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.05, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='child_phase_out_threshold_single',
            new_name='CTC_ps_0',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='CTC_ps_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='deduc_self_employ',
            new_name='ALD_SelfEmploymentTax_HC',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ALD_SelfEmploymentTax_HC',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='eitc_credit_rate_0',
            new_name='EITC_rt_0',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='EITC_rt_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='eitc_phase_out_rate_0',
            new_name='EITC_prt_0',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='EITC_prt_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='eitc_phase_out_threshold_0',
            new_name='EITC_ps_0',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='EITC_ps_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='fica',
            new_name='FICA_trt',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='FICA_trt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='foreign_earned_inc_exemp',
            new_name='FEI_ec_c',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='FEI_ec_c',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='forfeit_int_penalty',
            new_name='ALD_EarlyWithdraw_HC',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ALD_EarlyWithdraw_HC',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='II_prt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='individual_surtax',
            new_name='AMT_trt2',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='AMT_trt2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.02, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='individual_threshold',
            new_name='AMT_tthd',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='AMT_tthd',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='item_phase_out_rate',
            new_name='ID_prt',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_prt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.03, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='item_phase_out_threshold_single',
            new_name='ID_ps_0',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_ps_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='keogh_sep_deduc',
            new_name='ALD_KEOGH_SEP_HC',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ALD_KEOGH_SEP_HC',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='max_perc_forfeited',
            new_name='ID_crt',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_crt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.08, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='medical_floor',
            new_name='ID_Medical_frt',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_Medical_frt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.075, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='misc_floor',
            new_name='ID_Miscellaneous_frt',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_Miscellaneous_frt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=0.02, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='II_em',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='II_em_ps_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='qualify_number_child',
            new_name='ACTC_ChildNum',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ACTC_ChildNum',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=3, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='self_employ_health_deduc',
            new_name='ALD_SelfEmp_HealthIns_HC',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ALD_SelfEmp_HealthIns_HC',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='standard_amount_single',
            new_name='SS_thd85_3',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='SS_thd85_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='student_loan_deduc',
            new_name='ALD_StudentLoan_HC',
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ALD_StudentLoan_HC',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_rt4',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_rt_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_c_0',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_c_1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_c_2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_c_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_em_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_em_ps_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_tthd_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_c_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_ps_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='ID_ps_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk1_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk2_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk3_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk4_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk5_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk6_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_em_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_em_ps_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_Income_c_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_Aged_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_Aged_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ACTC_ChildNum',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='AMT_prt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='AMT_trt1',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='AMT_trt2',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='CTC_prt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_Casualty_frt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_Charity_crt_Asset',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_Charity_crt_Cash',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_Miscellaneous_frt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_crt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_Medical_frt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='ID_prt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMED_thd_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_thd1_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CG_thd2_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CTC_c_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='CTC_ps_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd1_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd2_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='Dividend_thd3_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='FEI_ec_c_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='FICA_mc_trt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='FICA_ss_trt',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='NIIT_thd_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_thd50_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_thd85_cpi',
            field=models.NullBooleanField(default=None),
            preserve_default=True,
        ),
    ]
