# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxbrain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='years',
            new_name='years_n',
        ),
    ]
