# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 20:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxbrain', '0002_auto_20180803_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='taxbrainrun',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
