# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxbrain', '0003_auto_20180803_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxbrainrun',
            name='error_text',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
    ]
