# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 16:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taxbrain', '0061_auto_20171220_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='UBI2',
            new_name='UBI_1820',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='UBI3',
            new_name='UBI_21',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='UBI1',
            new_name='UBI_u18',
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='deprecated_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='input_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='raw_input_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='outputurl',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taxsaveinputs',
            name='tax_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
