# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 20:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxbrain', '0062_auto_20180222_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsaveinputs',
            name='data_source',
            field=models.CharField(blank=True, default=b'PUF', max_length=20, null=True),
        ),
    ]
