# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-05 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taxbrain', '0069_auto_20180205_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputurl',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
