# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-16 19:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxbrain', '0070_auto_20180205_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsaveinputs',
            name='input_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='raw_input_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
