# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 20:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxbrain', '0071_auto_20180216_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsaveinputs',
            name='deprecated_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None),
        ),
    ]
