# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import webapp.apps.taxbrain.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxbrain', '0089_auto_20150314_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ACTC_ChildNum',
            new_name='ACTC_ChildNum',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ACTC_rt',
            new_name='ACTC_rt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ALD_Alimony_HC',
            new_name='ALD_Alimony_HC',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ALD_EarlyWithdraw_HC',
            new_name='ALD_EarlyWithdraw_HC',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ALD_KEOGH_SEP_HC',
            new_name='ALD_KEOGH_SEP_HC',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ALD_SelfEmp_HealthIns_HC',
            new_name='ALD_SelfEmp_HealthIns_HC',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ALD_SelfEmploymentTax_HC',
            new_name='ALD_SelfEmploymentTax_HC',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ALD_StudentLoan_HC',
            new_name='ALD_StudentLoan_HC',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMED_thd_0',
            new_name='AMED_thd_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMED_thd_1',
            new_name='AMED_thd_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMED_thd_2',
            new_name='AMED_thd_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMED_thd_3',
            new_name='AMED_thd_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMED_trt',
            new_name='AMED_trt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_em_0',
            new_name='AMT_em_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_em_1',
            new_name='AMT_em_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_em_2',
            new_name='AMT_em_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_em_3',
            new_name='AMT_em_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_em_ps_0',
            new_name='AMT_em_ps_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_em_ps_1',
            new_name='AMT_em_ps_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_em_ps_2',
            new_name='AMT_em_ps_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_em_ps_3',
            new_name='AMT_em_ps_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_prt',
            new_name='AMT_prt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_trt1',
            new_name='AMT_trt1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_trt2',
            new_name='AMT_trt2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_AMT_tthd',
            new_name='AMT_tthd',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_rt1',
            new_name='CG_rt1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_rt2',
            new_name='CG_rt2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_rt3',
            new_name='CG_rt3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_thd1_0',
            new_name='CG_thd1_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_thd1_1',
            new_name='CG_thd1_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_thd1_2',
            new_name='CG_thd1_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_thd1_3',
            new_name='CG_thd1_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_thd2_0',
            new_name='CG_thd2_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_thd2_1',
            new_name='CG_thd2_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_thd2_2',
            new_name='CG_thd2_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CG_thd2_3',
            new_name='CG_thd2_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CTC_c',
            new_name='CTC_c',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CTC_prt',
            new_name='CTC_prt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CTC_ps_0',
            new_name='CTC_ps_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CTC_ps_1',
            new_name='CTC_ps_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CTC_ps_2',
            new_name='CTC_ps_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_CTC_ps_3',
            new_name='CTC_ps_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_rt1',
            new_name='Dividend_rt1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_rt2',
            new_name='Dividend_rt2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_rt3',
            new_name='Dividend_rt3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd1_0',
            new_name='Dividend_thd1_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd1_1',
            new_name='Dividend_thd1_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd1_2',
            new_name='Dividend_thd1_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd1_3',
            new_name='Dividend_thd1_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd2_0',
            new_name='Dividend_thd2_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd2_1',
            new_name='Dividend_thd2_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd2_2',
            new_name='Dividend_thd2_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd2_3',
            new_name='Dividend_thd2_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd3_0',
            new_name='Dividend_thd3_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd3_1',
            new_name='Dividend_thd3_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd3_2',
            new_name='Dividend_thd3_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_Dividend_thd3_3',
            new_name='Dividend_thd3_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_c_0',
            new_name='EITC_c_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_c_1',
            new_name='EITC_c_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_c_2',
            new_name='EITC_c_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_c_3',
            new_name='EITC_c_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_prt_0',
            new_name='EITC_prt_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_prt_1',
            new_name='EITC_prt_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_prt_2',
            new_name='EITC_prt_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_prt_3',
            new_name='EITC_prt_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_ps_0',
            new_name='EITC_ps_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_ps_1',
            new_name='EITC_ps_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_ps_2',
            new_name='EITC_ps_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_ps_3',
            new_name='EITC_ps_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_rt_0',
            new_name='EITC_rt_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_rt_1',
            new_name='EITC_rt_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_rt_2',
            new_name='EITC_rt_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_EITC_rt_3',
            new_name='EITC_rt_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_FEI_ec_c',
            new_name='FEI_ec_c',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_FICA_trt',
            new_name='FICA_trt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_Casualty_frt',
            new_name='ID_Casualty_frt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_Charity_crt_Asset',
            new_name='ID_Charity_crt_Asset',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_Charity_crt_Cash',
            new_name='ID_Charity_crt_Cash',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_Miscellaneous_frt',
            new_name='ID_Miscellaneous_frt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_crt',
            new_name='ID_crt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_medical_frt',
            new_name='ID_medical_frt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_prt',
            new_name='ID_prt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_pe_0',
            new_name='ID_ps_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_pe_1',
            new_name='ID_ps_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_pe_2',
            new_name='ID_ps_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_ID_pe_3',
            new_name='ID_ps_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk1_0',
            new_name='II_brk1_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk1_1',
            new_name='II_brk1_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk1_2',
            new_name='II_brk1_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk1_3',
            new_name='II_brk1_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk2_0',
            new_name='II_brk2_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk2_1',
            new_name='II_brk2_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk2_2',
            new_name='II_brk2_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk2_3',
            new_name='II_brk2_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk3_0',
            new_name='II_brk3_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk3_1',
            new_name='II_brk3_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk3_2',
            new_name='II_brk3_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk3_3',
            new_name='II_brk3_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk4_0',
            new_name='II_brk4_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk4_1',
            new_name='II_brk4_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk4_2',
            new_name='II_brk4_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk4_3',
            new_name='II_brk4_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk5_0',
            new_name='II_brk5_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk5_1',
            new_name='II_brk5_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk5_2',
            new_name='II_brk5_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk5_3',
            new_name='II_brk5_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk6_0',
            new_name='II_brk6_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk6_1',
            new_name='II_brk6_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk6_2',
            new_name='II_brk6_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_brk6_3',
            new_name='II_brk6_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_em',
            new_name='II_em',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_em_ps_0',
            new_name='II_em_ps_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_em_ps_1',
            new_name='II_em_ps_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_em_ps_2',
            new_name='II_em_ps_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_em_ps_3',
            new_name='II_em_ps_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_rt1',
            new_name='II_prt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_rt2',
            new_name='II_rt1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_rt3',
            new_name='II_rt2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_rt4',
            new_name='II_rt3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_rt5',
            new_name='II_rt4',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_rt6',
            new_name='II_rt5',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_II_rt7',
            new_name='II_rt6',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_NIIT_thd_0',
            new_name='II_rt7',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_NIIT_thd_1',
            new_name='NIIT_thd_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_NIIT_thd_2',
            new_name='NIIT_thd_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_NIIT_thd_3',
            new_name='NIIT_thd_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_NIIT_trt',
            new_name='NIIT_thd_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_Income_c',
            new_name='NIIT_trt',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_percentage1',
            new_name='SS_Income_c',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_percentage2',
            new_name='SS_percentage1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_thd50_0',
            new_name='SS_percentage2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_thd50_1',
            new_name='SS_thd50_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_thd50_2',
            new_name='SS_thd50_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_thd50_3',
            new_name='SS_thd50_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_thd85_0',
            new_name='SS_thd50_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_thd85_1',
            new_name='SS_thd85_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_thd85_2',
            new_name='SS_thd85_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_SS_thd85_3',
            new_name='SS_thd85_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_STD_0',
            new_name='SS_thd85_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_STD_1',
            new_name='STD_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_STD_2',
            new_name='STD_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='_STD_3',
            new_name='STD_2',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='additional_aged_head',
            new_name='STD_3',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='additional_aged_jointly',
            new_name='STD_Aged_0',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='additional_aged_separately',
            new_name='STD_Aged_1',
        ),
        migrations.RenameField(
            model_name='taxsaveinputs',
            old_name='additional_aged_single',
            new_name='STD_Aged_2',
        ),
        migrations.RemoveField(
            model_name='taxsaveinputs',
            name='_II_prt',
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_em_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_em_ps_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='AMT_tthd_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_c_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='EITC_ps_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='ID_ps_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk1_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk2_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk3_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk4_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk5_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_brk6_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_em_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='II_em_ps_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='SS_Income_c_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_Aged_3',
            field=webapp.apps.taxbrain.models.CommaSeparatedField(default=None, max_length=200, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_Aged_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='taxsaveinputs',
            name='STD_cpi',
            field=models.NullBooleanField(default=None, blank=True, null=True),
            preserve_default=True,
        ),
    ]
