FROM opensourcepolicycenter/distributed:0.15.0

LABEL build="flask" version="0.0.1" date="2018-03-22"

USER root

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true

ENV HOST 0.0.0.0
ENV PORT 5050
ENV DEBUG true

# expose the app port
EXPOSE 80
EXPOSE 5050

# run the app server
CMD ["gunicorn", "--bind", "0.0.0.0:5050", "flask_server:app"]
