FROM continuumio/miniconda3
USER root
RUN  apt-get update && apt install libgl1-mesa-glx --yes
RUN mkdir /home/distributed
COPY requirements.txt home/distributed
WORKDIR /home/distributed
RUN conda config --append channels conda-forge
RUN conda install numpy>=1.12.1 pandas>=0.23.0 \
    matplotlib numba six bokeh>=0.12.7 mock xlrd \
    sphinx nomkl
RUN pip install -r requirements.txt
COPY script.sh /home/distributed
COPY ./Tax-Calculator /home/distributed/Tax-Calculator/
COPY ./B-Tax /home/distributed/B-Tax/
RUN bash script.sh
RUN mkdir /home/distributed/api
WORKDIR /home/distributed/api
