FROM distributed:latest

LABEL build="flask" version="0.0.1" date="2018-03-07"

USER root

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true

ENV HOST 0.0.0.0
ENV PORT 5000
ENV DEBUG true

# expose the app port
EXPOSE 80

# run the app server
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "flask_server:app"]
